Repository KMS-SmartCart/SmartCart-frontend, pull requests merged in 2024-09, with the labels that each got.

#2 [#1] Test: AWS Amplify CI/CD 테스트
  README.md
  src/pages/User/LoginPage.jsx
Labels: ✅ Test

#5 [#4] Feat: Backend 배포 URI 적용
  .env.development
  package.json
Labels: ✨ Feat

#8 [#7] Feat: 로그인 페이지 구현
  src/assets/images/carticon192.png
  src/assets/images/google.png
  src/assets/images/kakao.png
  src/assets/images/naver.png
  src/pages/User/LoginPage.jsx
Labels: ✨ Feat

#14 [#13] Docs: README 문서 내 기술스택 작성
  README.md
Labels: 📝 Docs

#15 [#13] Docs: Git컨벤션 파트 RollBack
  README.md
Labels: 📝 Docs

#16 [#13] Docs: README 배포 오타 수정
  README.md
Labels: 📝 Docs

#18 [#17] Docs: README 문서 내 시스템 및 네트워크 아키텍처 작성
  README.md
Labels: 📝 Docs

#20 [#19] Fix: 소셜 로그인 연동 URI 수정
  src/pages/User/LoginPage.jsx
Labels: 🐛 Fix

#22 [#9] Feat: 로그인 페이지 구현 3
  src/App.js
  src/pages/User/MainPage.jsx
Labels: ✨ Feat

#26 [#24] Feat: 내 정보 페이지 구현
  src/Component/Modal/DeleteUser.jsx
  src/Component/Navigation/BottomNav.jsx
  src/pages/User/LoginPage.jsx
  src/pages/User/MainPage.jsx
  src/pages/User/MyPage.jsx
Labels: ✨ Feat

#30 [#27] Feat: UI 수정
  src/pages/User/LoginPage.jsx
  src/pages/User/MainPage.jsx
  src/pages/User/MyPage.jsx
Labels: ✨ Feat

#37 [#36] Fix: PWA 앱 아이콘 및 네임 변경
  public/carticon128.png
  public/carticon192.png
  public/carticon512.png
  public/manifest.json
Labels: 🐛 Fix

#39 [#35] Feat: UI 수정
  src/pages/User/LoginPage.jsx
  src/pages/User/MainPage.jsx
  src/pages/User/MyPage.jsx
Labels: ✨ Feat

#42 [#41] Refactor: 로그인, 메인, 내정보 페이지 내 상단 UI 수정
  src/pages/User/LoginPage.jsx
  src/pages/User/MainPage.jsx
  src/pages/User/MyPage.jsx
Labels: ♻️ Refactor

#46 [#45] File: Component 디렉토리명 변경
  src/App.js
  src/components/Modal/ConfirmModal.jsx
  src/components/Modal/DeleteUserModal.jsx
  src/components/Navigation/BottomNav.jsx
  src/pages/Etc/CartPage.jsx
  src/pages/Etc/ItemInfoPage.jsx
  src/pages/Etc/LowestItemPage.jsx
  src/pages/User/LoginPage.jsx
  src/pages/User/MainPage.jsx
  src/pages/User/MyPage.jsx
Labels: 📁 File
